# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sedi报文转发系统
#apiurl: 'http://lekoxnfx.oicp.net:18020'
#apiurl: 'http://server.xunda.tech:8080'
#apiurl: 'http://192.168.1.100:8080'
#apiurl: 'http://localhost:8080'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://csw823197541.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:
#mapAPI_qq: "MN7BZ-IQQ36-LJ4S5-MKQUS-4HH6K-IQFGH"

# Build settings
markdown: kramdown
